// platform/host-app/components/ui/WaterRipple.tsx
import React, { useState, useCallback, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface WaterRippleProps {
  children: React.ReactNode;
  className?: string;
  onRippleComplete?: () => void;
  rippleColor?: string;
  disabled?: boolean;
}

/**
 * WaterRipple - Realistic SVG-based water distortion effect
 * Uses SVG filters to physically distort (refract) the DOM content beneath it.
 */
export function WaterRipple({
  children,
  className = "",
  onRippleComplete,
  rippleColor = "rgba(159, 157, 243, 0.4)",
  disabled = false,
}: WaterRippleProps) {
  const [isDistorting, setIsDistorting] = useState(false);
  const filterId = useRef(`water-filter-${Math.random().toString(36).substr(2, 9)}`);
  const turbulenceRef = useRef<SVGFETurbulenceElement>(null);
  const displacementRef = useRef<SVGFEDisplacementMapElement>(null);
  const animationRef = useRef<number>();

  // Ripples overlay state (visual rings)
  const [ripples, setRipples] = useState<{ id: number; x: number; y: number }[]>([]);
  const rippleIdCounter = useRef(0);

  const animateWater = (startTime: number) => {
    const elapsed = Date.now() - startTime;
    const duration = 1500;
    const progress = Math.min(elapsed / duration, 1);

    if (turbulenceRef.current && displacementRef.current) {
      // Animate base frequency to create "flow"
      const freq = 0.02 + progress * 0.05;
      turbulenceRef.current.setAttribute("baseFrequency", `${freq} ${freq}`);

      // Animate displacement scale: 0 -> 30 -> 0
      // Creates a strong distortion pulse
      let scale = 0;
      if (progress < 0.2) {
        scale = (progress / 0.2) * 20; // Ramp up
      } else {
        scale = 20 * (1 - (progress - 0.2) / 0.8); // Ramp down
      }
      displacementRef.current.setAttribute("scale", scale.toString());
    }

    if (progress < 1) {
      animationRef.current = requestAnimationFrame(() => animateWater(startTime));
    } else {
      setIsDistorting(false);
      if (displacementRef.current) displacementRef.current.setAttribute("scale", "0");
      onRippleComplete?.();
    }
  };

  const handleClick = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      if (disabled) return;

      // 1. Trigger Overlay Ripples
      const rect = e.currentTarget.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;
      const id = ++rippleIdCounter.current;
      setRipples((prev) => [...prev, { id, x, y }]);
      setTimeout(() => {
        setRipples((prev) => prev.filter((r) => r.id !== id));
      }, 1200);

      // 2. Trigger Distortion (Bending)
      setIsDistorting(true);
      if (animationRef.current) cancelAnimationFrame(animationRef.current);
      animateWater(Date.now());
    },
    [disabled, onRippleComplete],
  );

  useEffect(() => {
    return () => {
      if (animationRef.current) cancelAnimationFrame(animationRef.current);
    };
  }, []);

  return (
    <div
      className={`relative overflow-hidden ${className}`}
      onClick={handleClick}
      style={{
        // Apply the filter to the container. 
        // Note: This distorts EVERYTHING inside (text, images, borders).
        filter: isDistorting ? `url(#${filterId.current})` : 'none',
        willChange: isDistorting ? 'filter' : 'auto' // optimize rendering
      }}
    >
      {/* SVG Filter Definition */}
      <svg style={{ position: 'absolute', width: 0, height: 0, pointerEvents: 'none' }}>
        <defs>
          <filter id={filterId.current} x="-20%" y="-20%" width="140%" height="140%" filterUnits="objectBoundingBox" primitiveUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
            {/* Generate water texture noise */}
            <feTurbulence
              ref={turbulenceRef}
              type="fractalNoise"
              baseFrequency="0.02 0.02"
              numOctaves="1"
              seed="5"
              stitchTiles="stitch"
              result="noise"
            />
            {/* Displace the source graphic using the noise */}
            <feDisplacementMap
              ref={displacementRef}
              in="SourceGraphic"
              in2="noise"
              scale="0"
              xChannelSelector="R"
              yChannelSelector="G"
            />
          </filter>
        </defs>
      </svg>

      {children}

      <AnimatePresence>
        {ripples.map((ripple) => (
          <RippleEffect key={ripple.id} x={ripple.x} y={ripple.y} color={rippleColor} />
        ))}
      </AnimatePresence>
    </div>
  );
}

interface RippleEffectProps {
  x: number;
  y: number;
  color: string;
}

function RippleEffect({ x, y, color }: RippleEffectProps) {
  return (
    <>
      {[0, 1].map((i) => (
        <motion.div
          key={i}
          className="absolute pointer-events-none rounded-full"
          style={{
            left: x,
            top: y,
            transform: "translate(-50%, -50%)",
            border: `1.5px solid ${color}`,
            boxShadow: `0 0 20px ${color}`,
          }}
          initial={{ width: 0, height: 0, opacity: 0.6 }}
          animate={{
            width: [0, 400 + i * 100],
            height: [0, 400 + i * 100],
            opacity: [0.6, 0],
          }}
          exit={{ opacity: 0 }}
          transition={{
            duration: 1.5,
            delay: i * 0.2,
            ease: "easeOut",
          }}
        />
      ))}
    </>
  );
}

export default WaterRipple;

// miniapps-uniapp/shared/components/WaterRipple.vue
<template>
  <view class="water-ripple-container" :class="{ active: active }">
    <!-- SVG Filter Definition -->
    <svg class="water-ripple-svg" aria-hidden="true">
      <defs>
        <filter :id="filterId" x="-50%" y="-50%" width="200%" height="200%">
          <feTurbulence type="fractalNoise" baseFrequency="0.015 0.015" numOctaves="2" seed="42" result="noise" />
          <feDisplacementMap
            in="SourceGraphic"
            in2="noise"
            :scale="currentIntensity"
            xChannelSelector="R"
            yChannelSelector="G"
          />
        </filter>
      </defs>
    </svg>

    <!-- Content with filter applied -->
    <view class="water-ripple-content" :style="contentStyle">
      <slot />
    </view>

    <!-- Visual ripple rings -->
    <view
      v-for="ripple in ripples"
      :key="ripple.id"
      class="water-ripple-ring-container"
      :style="{ left: ripple.x + 'px', top: ripple.y + 'px' }"
    >
      <view
        v-for="i in 4"
        :key="i"
        class="water-ripple-ring"
        :style="{
          animationDelay: (i - 1) * 150 + 'ms',
          animationDuration: duration + 'ms',
          borderColor: tint,
          maxWidth: maxRadius * 2 + 'px',
          maxHeight: maxRadius * 2 + 'px',
        }"
      />
      <view
        class="water-ripple-splash"
        :style="{
          animationDuration: duration * 0.3 + 'ms',
          background: tint,
        }"
      />
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, watch, onUnmounted } from "vue";

const props = withDefaults(
  defineProps<{
    active?: boolean;
    duration?: number;
    maxRadius?: number;
    intensity?: number;
    tint?: string;
  }>(),
  {
    active: false,
    duration: 1500,
    maxRadius: 300,
    intensity: 30,
    tint: "rgba(159, 157, 243, 0.3)",
  },
);

const emit = defineEmits<{
  (e: "complete"): void;
}>();

interface Ripple {
  id: number;
  x: number;
  y: number;
}

const ripples = ref<Ripple[]>([]);
const rippleId = ref(0);
const currentIntensity = ref(0);

const filterId = computed(() => `water-ripple-filter-${rippleId.value}`);

const contentStyle = computed(() => ({
  filter: ripples.value.length > 0 ? `url(#${filterId.value})` : "none",
}));

// Create ripple at center
const createRipple = () => {
  const newRipple: Ripple = {
    id: rippleId.value++,
    x: 150, // Center position (adjust based on container)
    y: 300,
  };

  ripples.value.push(newRipple);
  currentIntensity.value = props.intensity;

  // Animate intensity decay
  const startTime = Date.now();
  const animate = () => {
    const elapsed = Date.now() - startTime;
    const progress = Math.min(elapsed / props.duration, 1);
    currentIntensity.value = props.intensity * (1 - progress);

    if (progress < 1) {
      requestAnimationFrame(animate);
    }
  };
  requestAnimationFrame(animate);

  // Remove ripple after duration
  setTimeout(() => {
    ripples.value = ripples.value.filter((r) => r.id !== newRipple.id);
    currentIntensity.value = 0;
    emit("complete");
  }, props.duration);
};

// Watch active prop
watch(
  () => props.active,
  (val) => {
    if (val) {
      createRipple();
    }
  },
);

onUnmounted(() => {
  ripples.value = [];
});
</script>

<style lang="scss">
.water-ripple-container {
  position: relative;
  width: 100%;
  height: 100%;
  overflow: hidden;
}

.water-ripple-svg {
  position: absolute;
  width: 0;
  height: 0;
  pointer-events: none;
}

.water-ripple-content {
  width: 100%;
  height: 100%;
  will-change: filter;
  transition: filter 0.3s ease-out;
}

.water-ripple-ring-container {
  position: absolute;
  transform: translate(-50%, -50%);
  pointer-events: none;
  z-index: 1000;
}

.water-ripple-ring {
  position: absolute;
  left: 50%;
  top: 50%;
  width: 20px;
  height: 20px;
  border: 2px solid;
  border-radius: 50%;
  transform: translate(-50%, -50%) scale(0);
  opacity: 0.8;
  animation: rippleExpand ease-out forwards;
  will-change: transform, opacity;
}

.water-ripple-splash {
  position: absolute;
  left: 50%;
  top: 50%;
  width: 30px;
  height: 30px;
  border-radius: 50%;
  transform: translate(-50%, -50%) scale(1);
  opacity: 0.6;
  animation: splashFade ease-out forwards;
  will-change: transform, opacity;
}

@keyframes rippleExpand {
  0% {
    transform: translate(-50%, -50%) scale(0);
    opacity: 0.8;
  }
  100% {
    transform: translate(-50%, -50%) scale(15);
    opacity: 0;
  }
}

@keyframes splashFade {
  0% {
    transform: translate(-50%, -50%) scale(1);
    opacity: 0.6;
  }
  100% {
    transform: translate(-50%, -50%) scale(0);
    opacity: 0;
  }
}
</style>
